# https://crontab.guru/crontab.5.html

name: checkForTranslations.yaml

on:

  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 * * * *' # Once every hour (minute 1)

jobs:
  update-translations:
    runs-on: windows-latest
    steps:
    - name: checkout remote
      uses: actions/checkout@v2
      with:
        repository: nvdaaddons/${{ github.event.repository.name }}
        ref: stable
    - name: Disable workflow on failure
      if: failure()
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: gh workflow disable ${{ github.workflow }}
    - name: Checkout main
      if: failure()
      uses: actions/checkout@v2

    - name: Push changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git remote add l10n https://github.com/nvdaaddons/${{ github.event.repository.name }}
        git fetch l10n
        git reset l10n/stable addon/doc addon/locale
        git commit -m "Update translations"
        git pull
        git push
        
        